""" Variables for Mock Datastore """

municipalities = ['Clairton', 'Duquesne', 'McKeesport', 'Pittsburgh', 
                  'Aspinwall', 'Avalon', 'Baldwin', 'Bell Acres', 'Bellevue', 
                  'Ben Avon', 'Ben Avon Heights', 'Bethel Park', 'Blawnox', 
                  'Brackenridge', 'Braddock', 'Braddock Hills', 'Bradford Woods', 
                  'Brentwood', 'Bridgeville', 'Carnegie', 'Castle Shannon', 
                  'Chalfant', 'Cheswick', 'Churchill', 'Coraopolis', 'Crafton', 
                  'Dormont', 'Dravosburg', 'East McKeesport', 'East Pittsburgh', 
                  'Edgewood', 'Edgeworth', 'Elizabeth', 'Emsworth', 'Etna', 
                  'Forest Hills', 'Fox Chapel', 'Franklin Park', 'Glassport', 
                  'Glen Osborne', 'Glenfield', 'Green Tree', 'Haysville', 
                  'Heidelberg', 'Homestead', 'Ingram', 'Jefferson Hills', 
                  'Leetsdale', 'Liberty', 'Lincoln', 'McKees Rocks', 'Millvale', 
                  'Monroeville', 'Mount Oliver', 'Munhall', 'North Braddock', 
                  'Oakdale', 'Oakmont', 'Pennsbury Village', 'Pitcairn', 
                  'Pleasant Hills', 'Plum', 'Port Vue', 'Rankin', 'Rosslyn Farms', 
                  'Sewickley', 'Sewickley Heights', 'Sewickley Hills', 
                  'Sharpsburg', 'Springdale', 'Swissvale', 'Tarentum', 
                  'Thornburg', 'Turtle Creek', 'Verona', 'Versailles', 
                  'Wall', 'West Elizabeth', 'West Homestead', 'West Mifflin', 
                  'West View', 'Whitaker', 'White Oak', 'Whitehall', 
                  'Wilkinsburg', 'Wilmerding', 'Aleppo', 'Baldwin', 'Collier', 
                  'Crescent', 'East Deer', 'Elizabeth', 'Fawn', 'Findlay', 
                  'Forward', 'Frazer', 'Hampton', 'Harmar', 'Harrison', '', 
                  'Indiana', 'Kennedy', 'Kilbuck', 'Leet', 'Marshall', 
                  'McCandless', 'Moon', 'Mt Lebanon', 'Neville', 'North Fayette', 
                  'North Versailles', 'Ohara', 'Ohio', 'Penn Hills', 'Pine', 
                  'Reserve', 'Richland', 'Robinson', 'Ross', 'Scott', 'Shaler', 
                  'South Fayette', 'South Park', 'South Versailles', 
                  'Springdale', 'Stowe', 'Upper St Clair', 'West Deer', 'Wilkins']
