# Generated by Django 3.2 on 2022-08-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(default='WPRDC', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='agreed_to_terms',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='category',
            field=models.CharField(choices=[('nonprofit', 'Housing and community development-focused nonprofit organizations '), ('government', 'Local, state, and federal government agencies and authorities'), ('philanthropy', 'Philanthropic organizations/Charitable foundations '), ('media', 'Media organizations'), ('student', 'Students'), ('researcher', 'Researchers'), ('mission_aligned_dev', 'Mission-aligned developers'), ('financial_inst', 'Financial Institutions')], default='researcher', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='conflicts',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='expected_account_tenure',
            field=models.IntegerField(default=100, help_text='in weeks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='intended_use',
            field=models.TextField(default='Research'),
            preserve_default=False,
        ),
    ]
