# Generated by Django 4.1 on 2022-09-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220806_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('ADMIN', '--ADMINISTRATOR--'), ('nonprofit', 'Housing and community development-focused nonprofit organizations '), ('government', 'Local, state, and federal government agencies and authorities'), ('philanthropy', 'Philanthropic organizations/Charitable foundations '), ('media', 'Media organizations'), ('student', 'Students'), ('researcher', 'Researchers'), ('mission_aligned_dev', 'Mission-aligned developers'), ('financial_inst', 'Financial Institutions')], max_length=64),
        ),
    ]
