# Generated by Django 5.1.4 on 2024-12-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FHLBFundingID',
            fields=[
                ('id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('projectidentifier_id', models.CharField(max_length=100)),
                ('projectindex_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'c1d26547-f13f-40bd-8363-e7fcc4584508',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FHLBRentalProjects',
            fields=[
                ('id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('fhlb_funding_id', models.TextField(blank=True, null=True)),
                ('parcel_count', models.IntegerField(blank=True, null=True)),
                ('hud_property_name', models.TextField(blank=True, null=True)),
                ('application_type_name', models.TextField(blank=True, null=True)),
                ('address_line_1_list', models.TextField(blank=True, null=True)),
                ('property_street_address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('county', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('zip_code', models.TextField(blank=True, null=True)),
                ('_50_percent_ami_limit', models.IntegerField(blank=True, db_column='50_percent_ami_limit', null=True)),
                ('_60_percent_ami_limit', models.IntegerField(blank=True, db_column='60_percent_ami_limit', null=True)),
                ('_80_percent_ami_limit', models.IntegerField(blank=True, db_column='80_percent_ami_limit', null=True)),
                ('greater_than_80_ami', models.IntegerField(blank=True, null=True)),
                ('assisted_units', models.IntegerField(blank=True, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('retention_expiration', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'afba564f-cc68-42f0-b37b-fc8d70e8ef47',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FHLBRentalProperties',
            fields=[
                ('id', models.IntegerField(db_column='_id', primary_key=True, serialize=False)),
                ('fhlb_funding_id', models.TextField(blank=True, null=True)),
                ('hud_property_name', models.TextField(blank=True, null=True)),
                ('application_type_name', models.TextField(blank=True, null=True)),
                ('property_street_address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('county', models.TextField(blank=True, null=True)),
                ('state', models.TextField(blank=True, null=True)),
                ('zip_code', models.TextField(blank=True, null=True)),
                ('assisted_units', models.IntegerField(blank=True, null=True)),
                ('units', models.IntegerField(blank=True, null=True)),
                ('retention_expiration', models.DateField(blank=True, null=True)),
                ('_50_percent_ami_limit', models.IntegerField(blank=True, db_column='50_percent_ami_limit', null=True)),
                ('_60_percent_ami_limit', models.IntegerField(blank=True, db_column='60_percent_ami_limit', null=True)),
                ('_80_percent_ami_limit', models.IntegerField(blank=True, db_column='80_percent_ami_limit', null=True)),
                ('greater_than_80_ami', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ecdbf89a-bbe7-4e82-b902-d6b774758d3a',
                'managed': False,
            },
        ),
    ]
